### ISSUE TITLE
Add detailed documentation

### ISSUE THREAD

**Issue by mostafa** [mostafa/grest#16]
I've recently stumbled upon a good project called [docsify](https://docsify.js.org/). I think we can use it to generate documents. [Read the Docs](https://readthedocs.org/) is also one of the options available.

**Comment by crytos** [comment]
Hey at read the docs some docs is missing can you help please

**Comment by mostafa** [comment]
Hey,

I should find some free time to complete it. In the mean time, if you have anything you want to know, tell me.

**Comment by crytos** [comment]
Okay, i will surely
