### ISSUE TITLE
using grest command

### ISSUE THREAD

**Issue by whatSocks** [mostafa/grest#330]
perhaps this is obvious, but I can't get the grest command to work. Using MacOS Catalina, python 3

```
 grest boop
zsh: //usr/local/Cellar/python@3.7/3.7.10_3/Frameworks/Python.framework/Versions/3.7/bin/grest: bad interpreter: c:\Python27\python.exe^M: no such file or directory
```

**Comment by mostafa** [comment]
Hey @whatSocks,

I haven't tested it on MacOS, yet the shebang at the start of the `grest` command points to `#!/usr/bin/python`. It's pretty strange that you are getting this error. This error usually happens on Windows machines.
> bad interpreter: c:\Python27\python.exe^M: no such file or directory

Can you give me more info?

**Comment by whatSocks** [comment]
hi @mostafa - I don't have that much more info.

I did `pip3 install pygrest` in a venv and couldn't get it to work at all, tried globally, then tried to resolve a permissions error, 

```
chmod +x /usr/local/Cellar/python@3.7/3.7.10_3/Frameworks/Python.framework/Versions/3.7/bin/grest
```
and then got the error above on `grest blablabla`

I'm using zsh and homebrew on mac

**Comment by mostafa** [comment]
I fixed the shebang and upgraded most of the packages to the latest version. So, please try to install version 2.3.0 of pygrest to see if it fixes your issue. Also, uninstall the previous versions.
